### ISSUE TITLE
[TEST] Who is using it?

### ISSUE THREAD

**Issue by sinchang** [sinchang/pr-welcome-badge#3]
leave a comment 🤟

**Comment by kapilG0** [comment]
@sinchang Can you please elaborate about issue ?

**Comment by sinchang** [comment]
Hi @kapilG0, Thanks for your attention,  it's not an issue, I created it to display the `PR Welcome` badge in the Readme.

**Comment by kapilG0** [comment]
> Hi @kapilG0, Thanks for your attention, it's not an issue, I created it to display the `PR Welcome` badge in the Readme.

Ok I am sorry I am new in open source that why it happens

**Comment by Prakash758758** [comment]
please close issue from your end if you created for testing prupose
